import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Index.module.scss'



export default function Home() {
  return (
    <>

      <title>24Money</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.Main}>
        <div className={styles.BodyImage}>
          <div className={styles.Body}>
            <h1> TWENTYFORMONEY</h1>

            <span>Portofolio</span>
            <div className={styles.Desc_about_container} data-aos="fade-up" >
              <div className={styles.Desc_social}>
                <a href="https://www.instagram.com/twenty4money/" target="_blank" >
                  <div className={styles.ImageSocial}>
                    <Image src='/assets/img/social/instagram.png' width={130} height={130} alt="Instagram" />
                    <h4>Instagram</h4>
                  </div>
                </a>
                <a href="https://www.youtube.com/channel/UCaAqyIxex60UWa74TdYlFmw" target="_blank" >
                  <div className={styles.ImageSocial}>
                    <Image src='/assets/img/social/youtube.png' width={130} height={130} alt="Youtube" />
                    <h4>Youtube</h4>
                  </div>
                </a>
              </div>

            </div>
            <div className={styles.Desc_about_container}>
              <div className={styles.Skill}>
                <div className={styles.Skill_Desc} data-aos="fade-up" >
                  <h1>HTML</h1>
                  <div data-aos="zoom-in" className={styles.Progress_HTML}/>
                </div>
                <div className={styles.Skill_Desc} data-aos="fade-up" >
                  <h1>CSS</h1>
                  <div data-aos="zoom-in"  className={styles.Progress_CSS}/>
                </div>
                <div className={styles.Skill_Desc} data-aos="fade-up" >
                  <h1>JAVASCRIPT</h1>
                  <div data-aos="zoom-in" className={styles.Progress_JAVASCRIPT}/>
                </div>
                <div className={styles.Skill_Desc} data-aos="fade-up" >
                  <h1>VB.NET</h1>
                  <div data-aos="zoom-in" className={styles.Progress_VBNET} />
                </div>
                <div className={styles.Skill_Desc} data-aos="fade-up" >
                  <h1>C#</h1>
                  <div data-aos="zoom-in" className={styles.Progress_CSHARP} />
                </div>
                <div className={styles.Skill_Desc} data-aos="fade-up" >
                  <h1>Python</h1>
                  <div data-aos="zoom-in" className={styles.Progress_PYTHON} />
                </div>
                
              </div>
            </div>
            <footer >
              <span > Copyright @ 2023 twentyformoney</span>
            </footer>
          </div>

        </div>
      </main>

    </>
  )
}
