import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Index.module.scss'


export default function Home() {
  return (
    <>
   
        <title>24Money</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <main className={styles.Main}>
          <div className={styles.BodyImage}>
            <div className={styles.Body}>
            <h1> TWENTYFORMONEY</h1>
            <span>Portofolio</span>
            <div className={styles.Desc_about_container}>
                    <div className={styles.Desc_social}>
                      <a href="https://www.instagram.com/twenty4money/" target="_blank">
                      <div className={styles.ImageSocial}>
                       <Image Src='assets/img/social/instagram.png' width={130}/>
                       <h4>Instagram</h4>
                      </div>
                      </a>
                      <a href="https://www.youtube.com/channel/UCaAqyIxex60UWa74TdYlFmw" target="_blank">
                      <div className={styles.ImageSocial}>
                       <Image Src='assets/img/social/youtube.png' width={130}/>
                       <h4>Youtube</h4>
                      </div>
                      </a>
                    </div>
                </div>
            </div>
          </div>
        </main>
        <footer>
          <span> Copyright @ 2023 twentyformoney</span>
        </footer>
    </>
  )
}
